#!/usr/bin/env lua

-- This script fetches the mime.types file from the Apache HTTPD repository,
-- parses it, sorts the MIME types and their associated file extensions,
-- and writes the result to a Lua module file.
--
-- USAGE: lua generate.lua > mimetypes/generated.lua
--
-- The output is canonicalized, so changes should show up as a clean diff.



-- Function to fetch the file content using curl
local function fetch_file(url)
  local cmd = string.format("curl -s %s", url)
  local pipe = io.popen(cmd)
  if not pipe then
      error("Failed to execute curl command.")
  end
  local content = pipe:read("*a")
  pipe:close()
  return content
end



--[[ Format of file is:
# COMMENT
MIME/TYPE EXTENSIONS
# MIME/TYPE
--]]
-- Function to parse the mime.types file into a hash table
local function parse_mime_types(content)
  local mime_table = {} -- dict
  for mime_type, extensions
  in content:gmatch"\n([^#/%s]+/[^/%s]+)[ \t]+([%g \t]+)"
  do
    if not mime_table[mime_type] then mime_table[mime_type] = {} end
    for extension in extensions:gmatch("%S+") do
      table.insert(mime_table[mime_type], extension)
    end
  end
  return mime_table
end



-- Function to sort the mime_table
local function sort_mime_table(mime_table)
  local result = {}
  local duplicates = {}
  -- Collect all MIME types, in array part of the table
  for mime_type, extensions in pairs(mime_table) do
      result[mime_type] = extensions  -- Copy values
      table.insert(result, mime_type) -- Add MIME type to array part
      table.sort(extensions)          -- Sort extensions
      for _, ext in ipairs(extensions) do
          duplicates[ext] = (duplicates[ext] or 0) + 1
      end
  end

  for ext, count in pairs(duplicates) do
      if count == 1 then
          duplicates[ext] = nil
      end
  end

  -- Sort MIME types in array part of the table
  table.sort(result)

  return result, duplicates
end



-- Main function to fetch, parse, sort, and write the mime.types file
local url = "https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types"
local content = fetch_file(url)
local sorted_mime_table, duplicates = sort_mime_table(parse_mime_types(content))

-- Write the sorted mime_table to a Lua module file
local file = io.stdout --io.open(output_file, "w")
file:write([[
-- This file is auto-generated from https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
-- DO NOT EDIT THIS FILE DIRECTLY
return {
]])
for _, mime_type in ipairs(sorted_mime_table) do
    local extensions = sorted_mime_table[mime_type]
    for _, extension in ipairs(extensions) do
        local str = '["' .. extension .. '"]' .. (" "):rep(13-#extension) .. ' = "' .. mime_type .. '",'
        if duplicates[extension] then
            str = "--" .. str .. " -- duplicate extension"
        else
            str = "  " .. str
        end
        file:write(str, "\n")
    end
end
file:write("}\n")
file:close()
