name: "Test"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit", "luajit-openresty"]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: true

    - uses: luarocks/gh-actions-lua@56eba09993704b908cc3c7c2753e630d18cb9696 # v14
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: luarocks/gh-actions-luarocks@95d2308a0aff36ad31ebadca493ed14853399842 # v7

    - name: Execute tests
      run: lua test.lua
